version: '3.1'

services:

  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    ports:
    - 9000:9000
    env_file:
      - ./.env
    volumes:
    - .:/workdir
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
    - postgres_data:/private/var/lib/postgresql/data

volumes:
  postgres_data:

