# Generated by Django 3.1.3 on 2020-12-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='growth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
