# Generated by Django 3.1.3 on 2020-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201212_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eating_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
