# Generated by Django 3.1.3 on 2020-12-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201212_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eating_amount',
        ),
    ]
